# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestDeletelocation():
  def setup_method(self, method):
    driver = webdriver.Chrome()
    vars = {}
  
  def teardown_method(self, method):
    driver.quit()
  
  def templatelocation(self):
    driver.get("http://www.learnwebservices.com/locations/server")
    driver.set_window_size(970, 445)
    driver.find_element(By.ID, "nameInput").click()
    driver.find_element(By.ID, "nameInput").send_keys(vars["name"])
    driver.find_element(By.ID, "coordsInput").click()
    driver.find_element(By.ID, "coordsInput").send_keys("13,13")
    driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
  
  def test_deletelocation(self):
    vars["name"] = driver.execute_script("return \'teszt_\'+Date.now()")
    templatelocation()
    driver.find_element(By.XPATH, "//tr[td[text()=\'vars["name"]\']]/td[6]/form/button").click()
    assert driver.find_element(By.CSS_SELECTOR, ".alert").text == "Location has deleted."
    elements = driver.find_elements(By.XPATH, "//td[text()=\'vars["name"]\']")
    assert len(elements) == 0
  
