# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestDelete():
  def setup_method(self, method):
    driver = webdriver.Chrome()
    vars = {}
  
  def teardown_method(self, method):
    driver.quit()
  
  def test_delete(self):
    driver.get("http://www.learnwebservices.com/locations/server")
    driver.set_window_size(1552, 840)
    driver.find_element(By.CSS_SELECTOR, "tr:nth-child(58) .btn").click()
    assert driver.switch_to.alert.text == "Are you sure?"
    driver.switch_to.alert.accept()
  
